let val;
const today = new Date();
let birthday = new Date('08-09-1995');
val = today.getMonth();
val = today.getDate();
val = today.getFullYear();
val = today.getHours;
val = today.getMinutes;
val = today.getSeconds();
val = today.getMilliseconds();
val = today.getTime();
birthday.setMonth(2);
birthday.setDate(12);
birthday.setFullYear(2025);
birthday.setHours(3);
birthday.setMinutes(30);
birthday.setSeconds(25);
console.log(birthday);