// log to console
console.log("hello world");
console.log(123);
console.log(true);
var greeting = "hello";
console.log(greeting);
console.log([1, 2, 3, 4]);
console.log({ a: 1, b: 2 });
console.table({ a: 1, b: 2 });
console.error("this is error");
console.clear();
console.warn("this is warning");
console.time("hello");
console.log("hello world");
console.log("hello world");
console.log("hello world");
console.log("hello world");
console.log("hello world");
console.log("hello world");
console.timeEnd("hello");